### ISSUE TITLE
Grouping of results

### ISSUE THREAD

**Issue by druwynings** [jgallen23/hubsearch#1]
Have you considered grouping search results that are simply forks of the same project?

**Comment by nicogranelli** [comment]
+1 

Or maybe just a checkbox to hide forks.

**Comment by jgallen23** [comment]
yeah, this should definitely be done.  Not a great experience if all the results are just 1 repo and all its forks

**Comment by nicogranelli** [comment]
does github api offer something for this?

**Comment by jgallen23** [comment]
Sort of. It lets you know if it's a fork or not, so the checkbox to hide should be fairly straight forward

**Comment by muescha** [comment]
but if it is a fork but there exists more recent commits then it should be marked as newer than the original
