### ISSUE TITLE
Search also in description of a project

### ISSUE THREAD

**Issue by muescha** [jgallen23/hubsearch#6]
compare:

http://projects.jga.me/hubsearch/#/Ruby/rubymotion

vs

700 results from 

https://github.com/search?q=RubyMotion&ref=commandbar&type=Repositories

**Comment by jgallen23** [comment]
When I built hubsearch, github search was pretty bad.  They've completely rebuilt search and now hubsearch has fallen behind.  Probably better off just using github search at this point.

**Comment by muescha** [comment]
but i like to sort by last commit and the score and github rank columns which is not possible at current github search ...

**Comment by muescha** [comment]
maybe the api v3 is better with the search
